import React from 'react';
import { ShieldAlert, Zap, DollarSign, CloudLightning, Shield } from 'lucide-react';

export interface PipelineIssue {
  ruleId: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  description: string;
  suggestion: string;
  line?: number;
}

export interface PipelineReport {
  pipelineId: string;
  totalIssues: number;
  criticalIssues: number;
  timeSavings: string;
  costSavings: string;
  issues: PipelineIssue[];
}

export function ValidationReport({ 
  report, 
  isEnterprise, 
  onFixIssue 
}: { 
  report: PipelineReport; 
  isEnterprise?: boolean; 
  onFixIssue?: (issue: PipelineIssue) => void;
}) {
  
  const getSeverityStyles = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return 'border-l-red-500 bg-red-500/5 text-red-200 border-t-white/5 border-r-white/5 border-b-white/5';
      case 'HIGH': return 'border-l-orange-500 bg-orange-500/5 text-orange-200 border-t-white/5 border-r-white/5 border-b-white/5';
      case 'MEDIUM': return 'border-l-yellow-500 bg-yellow-500/5 text-yellow-200 border-t-white/5 border-r-white/5 border-b-white/5';
      default: return 'border-l-blue-500 bg-blue-500/5 text-blue-200 border-t-white/5 border-r-white/5 border-b-white/5';
    }
  };

  const getSeverityBadge = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return 'bg-red-500/20 text-red-400 border border-red-500/20';
      case 'HIGH': return 'bg-orange-500/20 text-orange-400 border border-orange-500/20';
      case 'MEDIUM': return 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/20';
      default: return 'bg-blue-500/20 text-blue-400 border border-blue-500/20';
    }
  };

  return (
    <div className="w-full">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div className="bg-slate-900/50 backdrop-blur-xl border border-white/10 p-6 rounded-2xl flex items-center gap-4 hover:border-violet-500/30 transition-colors group">
          <div className="p-3 bg-red-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <ShieldAlert className="w-6 h-6 text-red-400" />
          </div>
          <div>
            <p className="text-sm text-slate-400 font-medium">Critical Issues</p>
            <p className="text-2xl font-bold text-slate-100">{report.criticalIssues}</p>
          </div>
        </div>

        <div className="bg-slate-900/50 backdrop-blur-xl border border-white/10 p-6 rounded-2xl flex items-center gap-4 hover:border-violet-500/30 transition-colors group">
          <div className="p-3 bg-fuchsia-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <Zap className="w-6 h-6 text-fuchsia-400" />
          </div>
          <div>
            <p className="text-sm text-slate-400 font-medium">Est. Time Savings</p>
            <p className="text-2xl font-bold text-slate-100">{report.timeSavings}</p>
          </div>
        </div>

        <div className="bg-slate-900/50 backdrop-blur-xl border border-white/10 p-6 rounded-2xl flex items-center gap-4 hover:border-violet-500/30 transition-colors group">
          <div className="p-3 bg-emerald-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <DollarSign className="w-6 h-6 text-emerald-400" />
          </div>
          <div>
            <p className="text-sm text-slate-400 font-medium">Est. Cost Savings</p>
            <p className="text-2xl font-bold text-slate-100">{report.costSavings}</p>
          </div>
        </div>
      </div>

      {/* SOC2 Compliance Export Button */}
      {isEnterprise && (
        <div className="mb-6 flex justify-end">
          <button
            onClick={() => {
              const content = `DEPLOYGUARD COMPLIANCE AUDIT REPORT
=====================================
Pipeline ID: ${report.pipelineId}
Status: ${report.criticalIssues > 0 ? 'NON-COMPLIANT' : 'COMPLIANT'}
Total Findings: ${report.totalIssues}
Critical Vulnerabilities: ${report.criticalIssues}
Date: ${new Date().toLocaleDateString()}

Findings Summary:
${report.issues.map((issue, idx) => `${idx + 1}. [${issue.severity}] ${issue.ruleId}: ${issue.description}\n   Suggestion: ${issue.suggestion}`).join('\n\n')}

=====================================
SOC2 Type II & ISO27001 Security Audit Log
Generated by DeployGuard Enterprise Compliance Engine.`;
              const blob = new Blob([content], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const link = document.createElement('a');
              link.href = url;
              link.download = `SOC2_Compliance_Audit_${report.pipelineId}.txt`;
              link.click();
              URL.revokeObjectURL(url);
            }}
            className="flex items-center gap-2 px-5 py-2.5 bg-violet-600 hover:bg-violet-700 text-white font-medium text-xs rounded-full shadow-lg transition-all active:scale-95"
          >
            <Shield className="w-4 h-4" /> Export SOC2 Compliance Report
          </button>
        </div>
      )}

      {/* Issues List */}
      <div className="bg-slate-900/50 backdrop-blur-xl border border-white/10 rounded-2xl overflow-hidden">
        <div className="px-6 py-4 border-b border-white/10 bg-slate-900/80 flex items-center gap-2">
          <Shield className="w-5 h-5 text-violet-400" />
          <h3 className="font-semibold text-slate-100">Security & Optimization Findings</h3>
        </div>
        
        <div className="p-6 space-y-4 max-h-[500px] overflow-y-auto custom-scrollbar">
          {report.issues.length === 0 ? (
            <div className="text-center py-12 text-slate-500">
              <ShieldCheck className="w-12 h-12 mx-auto mb-3 text-emerald-500/50" />
              <p>No issues found! Your pipeline is pristine.</p>
            </div>
          ) : (
            report.issues.map((issue, idx) => (
              <div 
                key={idx} 
                className={`p-5 rounded-xl border-l-4 border backdrop-blur-sm hover:scale-[1.01] transition-transform ${getSeverityStyles(issue.severity)}`}
              >
                <div className="flex justify-between items-start mb-2">
                  <div className="flex items-center gap-3">
                    <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold tracking-wide ${getSeverityBadge(issue.severity)}`}>
                      {issue.severity}
                    </span>
                    <span className="font-mono text-sm opacity-60 bg-black/20 px-2 py-0.5 rounded">{issue.ruleId}</span>
                  </div>
                  {issue.line && (
                    <span className="text-xs font-mono opacity-50 flex items-center gap-1">
                      Line {issue.line}
                    </span>
                  )}
                </div>
                <p className="text-sm mt-3 opacity-90 leading-relaxed font-medium">{issue.description}</p>
                <div className="mt-3 bg-black/20 p-3 rounded-lg flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
                  <div className="flex items-start gap-2">
                    <CloudLightning className="w-4 h-4 mt-0.5 opacity-60 flex-shrink-0" />
                    <p className="text-sm font-mono opacity-80">{issue.suggestion}</p>
                  </div>
                  {isEnterprise && onFixIssue && (
                    <button
                      onClick={() => onFixIssue(issue)}
                      className="px-3 py-1 bg-emerald-600 hover:bg-emerald-700 text-white font-medium text-xs rounded-full shadow transition-all flex items-center gap-1 self-end sm:self-auto flex-shrink-0"
                    >
                      <Zap className="w-3.5 h-3.5" /> AI Autofix
                    </button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
