import React from 'react';
import { ShieldAlert, Zap, DollarSign, CloudLightning, Shield, ShieldCheck } from 'lucide-react';

export interface PipelineIssue {
  ruleId: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  description: string;
  suggestion: string;
  line?: number;
}

export interface PipelineReport {
  pipelineId: string;
  totalIssues: number;
  criticalIssues: number;
  timeSavings: string;
  costSavings: string;
  issues: PipelineIssue[];
}

export function ValidationReport({ 
  report, 
  isEnterprise, 
  onFixIssue 
}: { 
  report: PipelineReport; 
  isEnterprise?: boolean; 
  onFixIssue?: (issue: PipelineIssue) => void;
}) {
  
  const getSeverityStyles = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': 
        return 'border-l-red-500 bg-red-50/20 text-neutral-800 border-y-[#F1F3F1] border-r-[#F1F3F1]';
      case 'HIGH': 
        return 'border-l-orange-500 bg-orange-50/20 text-neutral-800 border-y-[#F1F3F1] border-r-[#F1F3F1]';
      case 'MEDIUM': 
        return 'border-l-amber-500 bg-amber-50/20 text-neutral-800 border-y-[#F1F3F1] border-r-[#F1F3F1]';
      default: 
        return 'border-l-sky-500 bg-sky-50/20 text-neutral-800 border-y-[#F1F3F1] border-r-[#F1F3F1]';
    }
  };

  const getSeverityBadge = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': 
        return 'bg-red-100 text-red-800 border border-red-200';
      case 'HIGH': 
        return 'bg-orange-100 text-orange-800 border border-orange-200';
      case 'MEDIUM': 
        return 'bg-amber-100 text-amber-800 border border-amber-200';
      default: 
        return 'bg-sky-100 text-sky-800 border border-sky-200';
    }
  };

  return (
    <div className="w-full">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        
        {/* Critical Card */}
        <div className="bg-[#FAFBF9] border border-[#F1F3F1] p-6 rounded-2xl flex items-center gap-4 hover:border-red-500/20 transition-colors group">
          <div className="p-3 bg-red-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <ShieldAlert className="w-6 h-6 text-red-600" />
          </div>
          <div>
            <p className="text-sm text-[#5A635A] font-medium">Critical Issues</p>
            <p className="text-2xl font-bold text-black">{report.criticalIssues}</p>
          </div>
        </div>

        {/* Est. Time Savings Card */}
        <div className="bg-[#FAFBF9] border border-[#F1F3F1] p-6 rounded-2xl flex items-center gap-4 hover:border-[#1C2E1E]/20 transition-colors group">
          <div className="p-3 bg-emerald-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <Zap className="w-6 h-6 text-emerald-700" />
          </div>
          <div>
            <p className="text-sm text-[#5A635A] font-medium">Est. Time Savings</p>
            <p className="text-2xl font-bold text-black">{report.timeSavings}</p>
          </div>
        </div>

        {/* Est. Cost Savings Card */}
        <div className="bg-[#FAFBF9] border border-[#F1F3F1] p-6 rounded-2xl flex items-center gap-4 hover:border-[#1C2E1E]/20 transition-colors group">
          <div className="p-3 bg-emerald-500/10 rounded-xl group-hover:scale-110 transition-transform">
            <DollarSign className="w-6 h-6 text-emerald-700" />
          </div>
          <div>
            <p className="text-sm text-[#5A635A] font-medium">Est. Cost Savings</p>
            <p className="text-2xl font-bold text-black">{report.costSavings}</p>
          </div>
        </div>
      </div>

      {/* SOC2 Compliance Export Button */}
      {isEnterprise && (
        <div className="mb-6 flex justify-end">
          <button
            onClick={() => {
              const content = `DEPLOYGUARD COMPLIANCE AUDIT REPORT
=====================================
Pipeline ID: ${report.pipelineId}
Status: ${report.criticalIssues > 0 ? 'NON-COMPLIANT' : 'COMPLIANT'}
Total Findings: ${report.totalIssues}
Critical Vulnerabilities: ${report.criticalIssues}
Date: ${new Date().toLocaleDateString()}

Findings Summary:
${report.issues.map((rawIssue, idx) => {
  const ruleId = rawIssue.ruleId || (rawIssue as any).type || 'UNKNOWN';
  const description = rawIssue.description || (rawIssue as any).message || '';
  const suggestion = rawIssue.suggestion || (rawIssue as any).fix || '';
  return `${idx + 1}. [${rawIssue.severity}] ${ruleId}: ${description}\n   Suggestion: ${suggestion}`;
}).join('\n\n')}

=====================================
SOC2 Type II & ISO27001 Security Audit Log
Generated by DeployGuard Enterprise Compliance Engine.`;
              const blob = new Blob([content], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const link = document.createElement('a');
              link.href = url;
              link.download = `SOC2_Compliance_Audit_${report.pipelineId}.txt`;
              link.click();
              URL.revokeObjectURL(url);
            }}
            className="flex items-center gap-2 px-5 py-2.5 bg-[#1C2E1E] hover:bg-black text-white font-medium text-xs rounded-full shadow-lg transition-all active:scale-95"
          >
            <Shield className="w-4 h-4 text-emerald-400" /> Export SOC2 Compliance Report
          </button>
        </div>
      )}

      {/* Issues List */}
      <div className="bg-white border border-[#F1F3F1] rounded-2xl overflow-hidden shadow-sm">
        <div className="px-6 py-4 border-b border-[#F1F3F1] bg-[#FAFBF9] flex items-center gap-2">
          <Shield className="w-5 h-5 text-[#1C2E1E]" />
          <h3 className="font-semibold text-black">Security & Optimization Findings</h3>
        </div>
        
        <div className="p-6 space-y-4 max-h-[500px] overflow-y-auto custom-scrollbar bg-white">
          {report.issues.length === 0 ? (
            <div className="text-center py-12 text-[#738273]">
              <ShieldCheck className="w-12 h-12 mx-auto mb-3 text-emerald-600/60" />
              <p>No issues found! Your pipeline is pristine.</p>
            </div>
          ) : (
            report.issues.map((rawIssue, idx) => {
              const ruleId = rawIssue.ruleId || (rawIssue as any).type || 'UNKNOWN';
              const description = rawIssue.description || (rawIssue as any).message || '';
              const suggestion = rawIssue.suggestion || (rawIssue as any).fix || '';
              
              return (
                <div 
                  key={idx} 
                  className={`p-5 rounded-xl border-l-4 border backdrop-blur-sm hover:scale-[1.01] transition-transform ${getSeverityStyles(rawIssue.severity)}`}
                >
                  <div className="flex justify-between items-start mb-2">
                    <div className="flex items-center gap-3">
                      <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold tracking-wide ${getSeverityBadge(rawIssue.severity)}`}>
                        {rawIssue.severity}
                      </span>
                      <span className="font-mono text-xs text-[#738273] bg-[#FAFBF9] border border-[#F1F3F1] px-2 py-0.5 rounded">{ruleId}</span>
                    </div>
                    {rawIssue.line && (
                      <span className="text-xs font-mono text-[#738273] flex items-center gap-1">
                        Line {rawIssue.line}
                      </span>
                    )}
                  </div>
                  <p className="text-sm mt-3 text-neutral-800 leading-relaxed font-normal">{description}</p>
                  <div className="mt-3 bg-[#FAFBF9] border border-[#EAECE9] p-3 rounded-lg flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
                    <div className="flex items-start gap-2">
                      <CloudLightning className="w-4 h-4 mt-0.5 text-[#738273] flex-shrink-0" />
                      <p className="text-xs font-mono text-[#5A635A]">{suggestion}</p>
                    </div>
                    {isEnterprise && onFixIssue && (
                      <button
                        onClick={() => onFixIssue({ ...rawIssue, ruleId, description, suggestion })}
                        className="px-3.5 py-1.5 bg-[#1C2E1E] hover:bg-black text-white font-medium text-xs rounded-full shadow transition-all flex items-center gap-1 self-end sm:self-auto flex-shrink-0 active:scale-95"
                      >
                        <Zap className="w-3.5 h-3.5" /> AI Autofix
                      </button>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>
    </div>
  );
}
